### ISSUE TITLE
Fix cookie limitations in lecture-2

### ISSUE THREAD

**Issue by smf8** [1995parham-teaching/ie-lecture#45]
The cookie size constraints should be **at most ...** in [here](https://github.com/1995parham-teaching/ie-lecture/blob/main/content/lectures/lecture-2/index.html#L1018).

**Comment by 1995parham** [comment]
Hi @smf8, they are at least because they said the standard for who write browsers.

**Comment by smf8** [comment]
So this should be interpreted as: "Your browser should support at least 300 total cookies" ?

**Comment by 1995parham** [comment]
Exactly
