### ISSUE TITLE
The explaination of 3xx responses are not clear

### ISSUE THREAD

**Issue by rsharifnasab** [1995parham-teaching/ie-lecture#93]
In the specified slide about differences between different 3xx response codes, it is unclear what the difference between 302: Found and 307: Temporary Redirect is. Also although the name suggests, it is good to compare both of them with 301: Moved permanently.
![image](https://github.com/user-attachments/assets/e33d3e61-d1d2-4d7e-85fb-8ee210bf5e34)

I think it is a good idea to fix this or at least refer to [this SO link](https://stackoverflow.com/questions/2068418/whats-the-difference-between-a-302-and-a-307-redirect) or their MDN links [301](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301), [302](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302), and [307](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307),

**Comment by 1995parham** [comment]
Yes, I think having it here is good. I usually said the 307 and 301 is better than 302. What do you think?

**Comment by rsharifnasab** [comment]
I agree that 302 is not good but the slide content does not show that, especially with the misleading name of "found".

**Comment by 1995parham** [comment]
You are right, I will update it ASAP.
